# An optional generic message to reply after censoring
message: "Hi there, I just edited this for you."
# The required list of rules
rules:
    # A required pattern to scan for. Accepts anything that is a valid JavaScript regular expression
  - pattern: "(private_key|auth_token)=\w+"
    # The text to replace all matches with. Can refer to matching groups with $
    replacement: "$1=🔑"
    # Optional modifiers for the above regular expression. Defaults to "gi"
    modifier: "gi"
    # Optional message to reply to if this rule matches. If empty, no message is sent
    message: "Please **never post your private tokens**."
